config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  #get 'sessions/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'static_pages#home'

  #get 'static_pages/home'
  get  '/home', to: 'static_pages#home'
  #get 'static_pages/about'
  get '/about', to: 'static_pages#about'
  
  resources :users do
    member do
      get :followers, :following
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Shout out to 
    <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    for his
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  
  <div class="container">
    <%= link_to "Ritter", root_path, id: "logo" %>
    
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "What's this about?", about_path, id: "about" %></li>
        <li><%= link_to "See all users", users_path, id: "users" %></li>

        <% if logged_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              My account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete", id: "log_out" %>
              </li>
            </ul>
          </li>

        <% else %>
        
          <li><%= link_to "Sign up", new_user_path, id: "sign_up" %></li>
          <li><%= link_to "Log in", login_path, id: "log_in" %></li>

        <% end %>

      </ul>

    </nav>
    
  </div>
  
</header>

app/views/layouts/_shim.html.erb
   
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  
  <head>
    
    <title>
      <%= @title %>
    </title>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= render 'layouts/shim' %>
    
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    
    <div class="container">
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
      
    </div>
    
    <%= render 'layouts/footer' %>
    
    <%= debug(params) if Rails.env.development? %>
    
  </body>
  
</html>